### ISSUE TITLE
ConnectionLostException()

### ISSUE THREAD

**Issue by xamox** [debugger22/Jarvis#16]
I'm on ubuntu 12.04 with latest updates.  Ran apt-get install packages as recommended as well as pip install for requirements.

Ideas?

```
xamox@xamox-laptop:~/Software/Jarvis$ python jarvis.py 
Loading brain from data/jarvis.brn... done (96945 categories in 1.61 seconds)
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib audio/pcm_bluetooth.c:1614:(audioservice_expect) BT_GET_CAPABILITIES failed : Input/output error(5)
ALSA lib audio/pcm_bluetooth.c:1614:(audioservice_expect) BT_GET_CAPABILITIES failed : Input/output error(5)
ALSA lib audio/pcm_bluetooth.c:1614:(audioservice_expect) BT_GET_CAPABILITIES failed : Input/output error(5)
ALSA lib audio/pcm_bluetooth.c:1614:(audioservice_expect) BT_GET_CAPABILITIES failed : Input/output error(5)
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Cannot connect to server socket err = No such file or directory
Cannot connect to server socket
jack server is not running or cannot be started
Jarvis is listening...
Processing...
Error in processing loop:
Traceback (most recent call last):
  File "jarvis.py", line 54, in wakeup
    stt_response = stt_engine.get_text()
  File "/home/xamox/Software/Jarvis/src/google_stt.py", line 36, in get_text
    raise ConnectionLostException()
ConnectionLostException
^CAssertion 'pthread_mutex_destroy(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:81, function pa_mutex_free(). Aborting.
Aborted
```

**Comment by wallacesilva** [comment]
try change your audio card, if using on notebook try using hdmi or verify if your card is ok. Can be only this. Try restart your pc/notebook. good luck.

**Comment by DanielAndreasen** [comment]
I get some of the same errors, and I start to think it is a problem with the API key in `src/google_stt.py` line 29. It records fine, but unable to process it.

**Comment by debugger22** [comment]
Google deprecated tts and stt and hence Jarvis can't communicate anymore.
We'll have to make some mobile client for it.

Regards
Sudhanshu Mishra
www.sudhanshumishra.in

**Comment by DanielAndreasen** [comment]
Hi Sudhanshu,

What is the timeline for fixing this? It's a very nice program.

**Comment by debugger22** [comment]
> What is the timeline for fixing this?

I haven't decided about this but I'll try to talk to someone to make it. I'm busy these days on some other project.

> It's a very nice program.

Thanks! :)
